spring:
  datasource:
    url: jdbc:mysql://${database.server:localhost}:${database.port:3306}/stock_data?autoReconnect=true&useSSL=false
    username: ${database.username:root}
    password: ${database.password:Passw0rd}
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 5000
      initialization-fail-timeout: 5000
      login-timeout: 5000
      validation-timeout: 5000
  batch:
    initialize-schema: always
    job:
      enabled: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

fixedDelayMs: 1000


logging:
  level:
    com:
      josecponce:
        stockdata:
          iexdataloader:
            iextrading: trace
#    org:
#      springframework:
#        orm:
#          jpa: debug
