spring:
  datasource:
    url: jdbc:mysql://${database.server:localhost}:${database.port:3306}/stock_data?autoReconnect=true&useSSL=false
    username: ${database.username:root}
    password: ${database.password:Passw0rd}
    hikari:
      maximum-pool-size: 100
      idle-timeout: 30000
      connection-timeout: 10000
      initialization-fail-timeout: 5000
      login-timeout: 5000
      validation-timeout: 5000
  batch:
    initialize-schema: always
    job:
      enabled: false
#  jpa:
#    generate-ddl: true
#    show-sql: true

threadPoolSize: 20
timeRange: 5y
#don't go over 365 or data may start comming back in json instead of xml (unreadable)
treasuryRangeDays: 10000
fixedDelayMs: 30000

logging:
  level:
    org:
      springframework:
        batch:
          core:
            step:
              item:
                ChunkMonitor: error #this one is very annoying when doing batch jobs in parallel
    com:
      josecponce:
        stockdata:
          iexdataloader:
            iextrading: trace
#    org:
#      springframework:
#        orm:
#          jpa: debug
